export const DB_DATABASE_API = 'DB_DATABASE_API';
export const DB_DATABASE_PRODUCTS = 'DB_DATABASE_PRODUCTS';
export const DB_DATABASE_ORDERS = 'DB_DATABASE_ORDERS';
export const DB_DATABASE_PAYMENTS = 'DB_DATABASE_PAYMENTS';
